"""report rubric

Revision ID: 1c74f7c8358f
Revises: d299e76084db
Create Date: 2026-08-29 09:50:25.720210
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1c74f7c8358f'
down_revision: Union[str, None] = 'd299e76084db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_reports', schema=None) as batch_op:
        batch_op.drop_column('rubric')

    # ### end Alembic commands ###
