"""resume fields

Revision ID: 2fbdca2ea372
Revises: 9d4f26f0bdc2
Create Date: 2026-08-28 01:35:54.620409
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2fbdca2ea372'
down_revision: Union[str, None] = '9d4f26f0bdc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resume_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('resume_summary')
        batch_op.drop_column('resume_text')

    # ### end Alembic commands ###
