"""report session_id for replay

Revision ID: 750b7d1a9c9c
Revises: 2fbdca2ea372
Create Date: 2026-08-28 01:41:59.064393
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '750b7d1a9c9c'
down_revision: Union[str, None] = '2fbdca2ea372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_reports', schema=None) as batch_op:
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
