"""session coverage_state

Revision ID: 9e050e30c83a
Revises: 1c74f7c8358f
Create Date: 2026-08-29 11:00:54.480567
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e050e30c83a'
down_revision: Union[str, None] = '1c74f7c8358f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverage_state', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('coverage_state')

    # ### end Alembic commands ###
