"""structured diagram model+analysis

Revision ID: d299e76084db
Revises: 750b7d1a9c9c
Create Date: 2026-08-29 09:41:37.389679
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd299e76084db'
down_revision: Union[str, None] = '750b7d1a9c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagram_model', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('diagram_analysis', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('diagram_analysis')
        batch_op.drop_column('diagram_model')

    # ### end Alembic commands ###
